ministryofjustice/hmpps-helm-charts

charts/generic-prometheus-alerts/Chart.yaml
charts/generic-prometheus-alerts/templates/_helpers.tpl

Similarly named applications in the same namespace (i.e. `something-api`
and `something-ui`) were producing the same UID as they were producing
the same string up until the last few characters, which we had to
truncate due to the length limitations.

Make the dashboard UID generation a bit more complex... :(

---

charts/generic-service/Chart.yaml
charts/generic-service/templates/networkpolicy.yaml
charts/generic-service/templates/servicemonitor.yaml
charts/generic-service/values.yaml

This allows users to easily expose prometheus metrics from their
applications.
- The networkpolicy is needed to allow prometheus access to your
applications namespace.
- The servicemonitor instructs prometheus where (and how often) to
scrape metrics from.

Allow for the easy scraping of custom (prometheus) metrics

---

README.md

Adds kink to service dependency tracking page (https://structurizr.com/share/56937/documentation/*#2)
The hypothesis is that it will help people looking for examples find ones in the wild.
**Depends on**
- https://github.com/ministryofjustice/hmpps-architecture-as-code/pull/149
[This is how it will look](https://github.com/ministryofjustice/hmpps-architecture-as-code/pull/149#issuecomment-974062215)

Link to service dependency tracking page

---

charts/generic-prometheus-alerts/Chart.yaml
charts/generic-prometheus-alerts/templates/_helpers.tpl

We're getting a lot of duplicate uid errors in the grafana dashboard
importer and I was noticing some of our dashboards ended up with the
same UID... :-/

Improve the uniqueness of the generated UID's

---

.github/workflows/alert-test.yml
.gitignore
Makefile
README.md
charts/generic-prometheus-alerts/Chart.yaml
charts/generic-prometheus-alerts/RUNBOOK.md
charts/generic-prometheus-alerts/ci/test-application/Chart.tpl.yaml
charts/generic-prometheus-alerts/ci/test-application/Chart.yaml
charts/generic-prometheus-alerts/ci/test-application/values.yaml
charts/generic-prometheus-alerts/ci/tests/application-alerts-tests.yaml
charts/generic-prometheus-alerts/templates/application-alerts.yaml
compile-generic-prometheus-alert-test-app-yaml.sh

This will fix an issue we've seen with false positives [ref PUD-1215] where a job has failed once (from a cron job), but successful runs have completed successfully, but the alert has still persisted.
A major component of this PR is introducing unit tests to the alert rules...

Fix failed job false positives

---

charts/generic-service/Chart.yaml
charts/generic-service/templates/deployment.yaml
charts/generic-service/templates/servicemonitor.yaml
charts/generic-service/values.yaml

ref: https://mojdt.slack.com/archives/C0223AGGQU8/p1643216466075700
The security team see metrics exposed publicly as an information leakage
vulnerability - this allows teams to serve their metrics on a port
different to the main service so they are no longer exposed as part of
the service outside of the cluster.

Allow prometheus metrics to be served from a custom port

---

charts/generic-service/Chart.yaml
charts/generic-service/templates/service.yaml

If the user has defined a custom port for metrics we need to also expose
this port within the service in order for prometheus to pick it up.

Bugfix: Fix the ServiceMonitor with a custom metrics port

---

charts/generic-service/Chart.yaml
charts/generic-service/templates/ingress.yaml

networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

update ingress api

---

charts/generic-data-analytics-extractor/Chart.yaml
charts/generic-data-analytics-extractor/values.yaml

This change is to make sure that extracted data is picked up by the register-my-data injest pipeline which runs at 1am

DCS-1515 change to generic data extractor cron job scheduling

---

charts/generic-service/Chart.yaml
charts/generic-service/README.md
charts/generic-service/templates/ingress.yaml
charts/generic-service/templates/ingress_v1_2.yaml
charts/generic-service/values.yaml

allow subject alternative names to get around domain length limit that results in the certificate being unable to renew.
if an ingress.host is longer than 64 chars then a cert is generated with that CN. Having a CN longer than 64 chars causes the cert to not be accepted. If there are multiple tls.hosts (one becomes a CN and the others SANs), if one is less than 64 chars it will be chosen as the CN and the cert will be good

allow-subject-alternative-names-to-get-around-domain-length-limit

---

charts/generic-service/Chart.yaml
charts/generic-service/templates/hpa.yaml

In lieu of : 
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/apiversion-changes-hpa-k8s-1-25.html#updating-horizontalpodautoscaler-api-version-for-cloud-platform-removed-kubernetes-v1-25
- Upgrade Horizontal Pod Autoscaler version in hpa.yaml
- Bump version number

PIC 3363 k8s upgrade removing deprecated APIs

---

.gitignore
README.md
charts/generic-data-analytics-extractor/Chart.yaml
charts/generic-data-analytics-extractor/README.md
charts/generic-data-analytics-extractor/templates/_helpers.tpl
charts/generic-data-analytics-extractor/templates/cronjob.yaml
charts/generic-data-analytics-extractor/values.yaml

This PR comes about after trying to use the `generic-data-analytics-extractor` helm chart in the `hmpps-education-and-work-plan-api` project.
The problem it solves is that of the generated name, which in the original code is this:
```
kind: CronJob
metadata:
name: {{ .Release.Name }}-data-analytics-extractor
labels:
```
The name is simply a concatenation of the release name and `-data-analytics-extractor` which for our project resulted in `hmpps-education-and-work-plan-api-data-analytics-extractor`. This this fails to deploy as the resource name is limited at 52 characters:
> Error: UPGRADE FAILED: failed to create resource: CronJob.batch "hmpps-education-and-work-plan-api-data-analytics-extractor" is invalid: [spec.jobTemplate.spec.template.spec.containers[0].env[5].valueFrom.secretKeyRef …

RR-446 - Add nameOverride to generic-data-analytics-extractor

---

charts/generic-service/Chart.yaml
charts/generic-service/README.md
charts/generic-service/templates/retry-dlq-cronjob.yaml
charts/generic-service/values.yaml

This is the output with `retryDlqCronjob` and `scheduledDowntime` enabled
```# Source: hmpps-person-record/charts/generic-service/templates/retry-dlq-cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
name: hmpps-person-record-queue-housekeeping-cronjob
labels:
helm.sh/chart: generic-service-2.10.1
app: hmpps-person-record
release: hmpps-person-record
app.kubernetes.io/version: "latest"
app.kubernetes.io/managed-by: Helm
spec:
schedule: "*/10 7-21 * * 1-5"
concurrencyPolicy: Forbid
failedJobsHistoryLimit: 5
startingDeadlineSeconds: 600
successfulJobsHistoryLimit: 5
jobTemplate:
spec:
template:
spec:
serviceAccountName: person-record-service
containers:
- name: housekeeping
image: ghcr.io/ministryofjustice/hmpps-devops-tools
args:
- /bin/sh
- -c
- curl -XPUT --connect-timeout 5 …
```

CPR-142 add retry dlq cronjob with support for scheduled downtime

---

charts/generic-service/Chart.yaml
charts/generic-service/README.md
charts/generic-service/values.yaml

We are seeing lots of pod restarts around 6am down to database connection failures. It seems that the database startups happen around 615am, so any pods which depend on a database connection will be bound to fail.

CPR-174 delay restart from scheduled downtime to 630 to allow for RDS

---

charts/generic-service/Chart.yaml
charts/generic-service/values.yaml

This change eliminates the kubectl warnings regarding missing securityContext settings.

Add default securityContext values to align with cluster enforced values (via gatekeeper mutations).

---

charts/generic-service/Chart.yaml
charts/generic-service/ci/test-values.yaml
charts/generic-service/templates/prison-postgres-database-restore.yaml
charts/generic-service/templates/retry-dlq-cronjob.yaml
charts/generic-service/templates/scheduled-downtime-cronjob.yaml
charts/generic-service/values.yaml

securityContext is now set for all containers that are part of cronjobs.
Added fix for warning messages about using `latest` image tag.

Add default securityContext to all containers.

---

charts/generic-service/Chart.yaml
charts/generic-service/templates/scheduled-downtime-cronjob.yaml

```mark.rees@MJ004359 hmpps-person-record % kubectl get jobs -n hmpps-person-record-dev                                                
NAME                                   COMPLETIONS   DURATION   AGE
hmpps-person-record-startup-28637670   0/1           2m33s      2m42s
mark.rees@MJ004359 hmpps-person-record % kubectl logs job.batch/hmpps-person-record-startup-28637670 -n hmpps-person-record-dev
error: Expected replicas to be 0, was 1
```
This is a problem in British Summer Time if you start work a bit early and merge a pull request.
This job has now failed and will alert, although the number of replicas is as desired. I don't think we need to check the number of replicas on startup. We don't do so on shutdown

CPR-307 do not fail startup cronjob if the number of replicas is not 0

---

charts/generic-service/Chart.yaml
charts/generic-service/README.md

Link to documentation https://kubernetes.io/docs/concepts/configuration/secret/#use-case-dotfiles-in-a-secret-volume
in the README.md to describe how to mount k8s secrets.
Update the Helm Chart version to `3.6.2` to pass automated tests

Update README to describe how to mount volumed k8s secrets

---

charts/generic-data-analytics-extractor/Chart.yaml
charts/generic-data-analytics-extractor/templates/cronjob.yaml
charts/generic-data-analytics-extractor/values.yaml

* Allows container resources to be defined as part of the template. Useful for larger data extraction use cases.

Add resources definition to the data extractor template

---

charts/generic-service/Chart.yaml
charts/generic-service/prison-postgres-restore.sh

Currently if the pod is destroyed or removed for any reason including failures and timeouts, the database can be left incomplete with missing constraints and indices. Adding a parameter to ensure the entire thing is ran in a single transaction.

Make restore transactional to prevent leaving db in an inconsistent state

---

charts/generic-service/Chart.yaml
charts/generic-service/README.md
charts/generic-service/prison-postgres-restore.sh
charts/generic-service/values.yaml

We maintain a mixed set of HMPPS applications, some of them are legacy and still using Rails. We are already using the db restore job with kotlin/flyway apps but would be great to also be able to use it in our Rails apps, where we use this helm chart successfully.
This PR allows supplying an optional `MIGRATIONS_VENDOR` env variable to `postgresDatabaseRestore`. If not provided, current behaviour (flyway) remains intact, thus the minor patch version.
Will be very easy to expand this to other migration types, if necessary in the future.

Support active record in postgres restore script

---

charts/generic-service/Chart.yaml
charts/generic-service/README.md
charts/generic-service/templates/scheduled-downtime-cronjob.yaml
charts/generic-service/values.yaml

Non-production RDS databases on Cloud Platform are stopped between 10pm-6am UTC, so for most services the time zone should be left as "Etc/UTC". However, for other services that have dependencies with a downtime schedule in a different timezone (e.g. "Europe/London"), then this allows them to ensure the schedules match.
Specifically, this allows probation integration services that connect to the Delius database to ensure the pods are offline while the database is offline (9PM-6AM Europe/London time).

PI-2965 Add support for timeZone in scheduled downtime job

---

charts/generic-prometheus-alerts/Chart.yaml
charts/generic-prometheus-alerts/ci/tests/application-alerts-tests.yaml
charts/generic-prometheus-alerts/ci/tests/ingress-alerts-tests-hourly.yaml
charts/generic-prometheus-alerts/ci/tests/ingress-alerts-tests.yaml
charts/generic-prometheus-alerts/templates/application-alerts.yaml
charts/generic-prometheus-alerts/templates/aws-elasticache-alerts.yaml
charts/generic-prometheus-alerts/templates/aws-rds-alerts.yaml
charts/generic-prometheus-alerts/templates/aws-sns-alerts.yaml
charts/generic-prometheus-alerts/templates/aws-sqs-alerts.yaml
charts/generic-prometheus-alerts/templates/ingress-alerts.yaml
charts/generic-prometheus-alerts/values.yaml

Update application rules regex:
- the regex used to match against pods is now more precise.
- now matching the standard k8s pod naming (for a deployment/replicaset) which
includes random characters.
e.g. [deployment-name]-[random 4-10 alpha chars]-[random 5 alpha chars]
See https://github.com/kubernetes/kubernetes/issues/121687  - for discussion on the length of the length of random chars in the ReplicaSet name.  I've decided on minimum of 4 chars as safe bet that we get a match in prometheus.  The issue suggest matching on `ownerReferences ` however these are not available to in prometheus.

Update ingress and application rules regex.  Fix all summary, message, dashboard annotations - make them all consistent.

---

Makefile
charts/generic-prometheus-alerts/Chart.yaml
charts/generic-prometheus-alerts/ci/test-application/values.yaml
charts/generic-prometheus-alerts/ci/test-business-hours/values.yaml
charts/generic-prometheus-alerts/ci/tests/aws-opensearch-alerts-tests.yaml
charts/generic-prometheus-alerts/templates/aws-opensearch-alerts.yaml
charts/generic-prometheus-alerts/values.yaml

Creates alerts according to https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html (or at least the ones we can cover with the Prometheus metrics we have)
* Cluster status red / yellow
* Free storage space
* Blocked writes
* Automated snapshot failure
* High CPU utilisation
* High JVM memory pressure
Tested locally, here: https://mojdt.slack.com/archives/C033HPR0W91/p1750237464697489

PI-3145 Alerts for OpenSearch
